### ISSUE TITLE
Frecuency?

### ISSUE THREAD

**Issue by guillermobr** [mwouts/world_bank_data#13]
Hi.. im missing something or all the data i can request is per year ?

Thanks!

**Comment by mwouts** [comment]
Hello @guillermobr , good question! I think so. For further information, you can have a look at the [Workbank site](https://datahelpdesk.worldbank.org/knowledgebase/articles/77928-do-you-have-quarterly-monthly-or-higher-frequency) itself, which I quote below:

> *Do you have quarterly, monthly or higher frequency data?*

> Most social and economic data are collected and reported annually or less often. Some economic and financial data are available on monthly or quarterly basis (for example, the Global Economic Monitor (GEM)) and some are reported daily (for instance, the World Bank Projects & Operations database is updated on a daily basis). To see the frequency of updates for specific data, please consult the World Bank data catalogue, which provides details on the frequency of updates for each dataset.

**Comment by guillermobr** [comment]
thanks :)
