### ISSUE TITLE
Creating DataFrame from indicator Series

### ISSUE THREAD

**Issue by mehdizouari** [mwouts/world_bank_data#14]
Thanks for sharing. I was trying to create tables from a couple of the indicators but continuously running into the same error. Would you please be able to help me out? (Screenshot attached)
![Series_to_dataframe](https://user-images.githubusercontent.com/64650761/81636577-ccb7b800-93d9-11ea-8fe2-1302518579d1.png)

**Comment by mwouts** [comment]
Hello @mehdizouari , thanks for asking.
If you want to turn the series into a DataFrame, why not using `reset_index()`?
For instance:
```
wb.get_series('NY.GDP.MKTP.KD.ZG', mrv=1).reset_index()
```
![Screenshot from 2020-05-14 22-56-33](https://user-images.githubusercontent.com/29915202/81985193-392ef300-9636-11ea-9132-3fbba6f79802.png)

Also, if you're bothered by the multiindex, note that you can use `simplify_index` like here:
![image](https://user-images.githubusercontent.com/29915202/81985345-6b405500-9636-11ea-8f48-aa500de2644a.png)

**Comment by mehdizouari** [comment]
Thank you so much. I was stuck with this for days now. Huge help for me to be able to progress my capstone project. Thanks again

**Comment by mwouts** [comment]
My pleasure! Good luck with your project.
