### ISSUE TITLE
Give better error messages on failed download

### ISSUE THREAD

**Issue by bcipolli** [mwouts/world_bank_data#7]
There are a number of metrics that fail to download. Some give a meaningful error ("400 bad request", with URL printed), while others give a cryptic "Expecting value: line 1 column 1 (char 0)".

Instead of printing cryptic errors, handle more gracefully.

**Comment by mwouts** [comment]
Hello @bcipolli , sure, that is a great idea!
Could you please provide a sample code snippet that produces that error?
I'd be interesting in fixing both the error message, and if possible, the download itself.

**Comment by mwouts** [comment]
I plan to release an update of the package soon. Would you like to contribute an example that produces the error? Thanks.
